language: elixir
elixir:
  - '1.6'
otp_release:
  - '20.2'

before_script:
  - MIX_ENV=test mix compile

script:
  - MIX_ENV=test mix do compile, coveralls.json

after_success:
  - bash <(curl -s https://codecov.io/bash)


